apiVersion: v1
kind: PersistentVolume
metadata:
  name: productservice-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data  # Change this to a suitable path or storage backend
  storageClassName: manual
